name: Update Steam Games List

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

# Das hier ist neu und gibt der Action die Erlaubnis, die Datei zu speichern!
permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Geupdatet auf v4

      - name: Install Node.js
        uses: actions/setup-node@v4 # Geupdatet auf v4
        with:
          node-version: '20' # Geupdatet auf eine aktuelle Version

      - name: Install Dependencies
        run: npm install axios

      - name: Run Script
        run: node fetch_steam.js

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add meine_spiele.txt
          git commit -m "Update Steam games list" || exit 0
          git push
